In [8]:
# 统计一下代码量
files=[
    r"C:\code\log-process\loger.py",
    r"C:\code\log-process\logReader.py",
    r"C:\code\log-process\main.py",
    r"C:\code\log-process\pages\bond_level\page.py",
    r"C:\code\log-process\pages\bond_level\scripy.py",
    r"C:\code\log-process\pages\save_obtial\page.py",
    r"C:\code\log-process\pages\save_obtial\script.py",
    r"C:\code\log-process\server\server.py",
    r"C:\code\log-process\server\templates\index.html"
]
num=0
clear_num=0
for file in files:
    with open(file,'r',encoding='utf-8') as f:
        #lines=f.read().split('\n')
        lines=f.readlines()
        num+=len(lines)
        for line in lines:
            if len(line)!=0:
                clear_num+=1
print(num,clear_num)

1146 1146


In [23]:
import numpy as np
import math
def function(centerPos,aroundPos,alphas,cs,ts): # 为了代码可读性，可以适当写出来罗嗦点的代码
        x,y,z=aroundPos
        x0,y0,z0=centerPos
        R=np.sum((centerPos-aroundPos)**2,axis=0,keepdims=True)
        def psx(a):
            return (2*a/math.pi)**(3/4)*2*a**0.5*(x-x0)*math.e**(-1*a*R)
        def psy(a):
            return (2*a/math.pi)**(3/4)*2*a**0.5*(y-y0)*math.e**(-1*a*R)
        def psz(a):
            return (2*a/math.pi)**(3/4)*2*a**0.5*(z-z0)*math.e**(-1*a*R)
        px2=sum([c*psx(a) for c,a in zip(cs[:-1],alphas[:-1])])  # 对于3-21
        py2=sum([c*psy(a) for c,a in zip(cs[:-1],alphas[:-1])])
        pz2=sum([c*psz(a) for c,a in zip(cs[:-1],alphas[:-1])])
        px3=cs[-1]*psx(alphas[-1])
        py3=cs[-1]*psy(alphas[-1])
        pz3=cs[-1]*psz(alphas[-1])
        ps=[px2,py2,pz2,px3,py3,pz3]
        mo=sum([t*p for t,p in zip(ts,ps)])
        return mo

In [78]:
space=np.arange(-1,2,1)
aroundPos=np.array([each.flatten() for each in np.meshgrid(space,space,space)])
centerPos=np.array([0,0,0]).reshape(3,1)

In [79]:
centerPos.shape,aroundPos.shape,(centerPos+aroundPos)

((3, 1),
 (3, 27),
 array([[-1, -1, -1,  0,  0,  0,  1,  1,  1, -1, -1, -1,  0,  0,  0,  1,
          1,  1, -1, -1, -1,  0,  0,  0,  1,  1,  1],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [-1,  0,  1, -1,  0,  1, -1,  0,  1, -1,  0,  1, -1,  0,  1, -1,
          0,  1, -1,  0,  1, -1,  0,  1, -1,  0,  1]]))

In [62]:
R=np.sum((centerPos-aroundPos)**2,axis=0,keepdims=True).shape

In [63]:
x,y,z=aroundPos
x0,y0,z0=centerPos

In [64]:
function(centerPos=centerPos,aroundPos=aroundPos,alphas=[1,2,3,4],cs=[4,3,2,1],ts=[1,2,3,4,5,6]).shape

(8000,)

In [16]:
x

array([-1, -1,  0,  0, -1, -1,  0,  0])

In [17]:
y

array([-1, -1, -1, -1,  0,  0,  0,  0])

In [18]:
z

array([-1,  0, -1,  0, -1,  0, -1,  0])

In [16]:
import random
def test(n):
    if n<=1:
        return 'hello' 
    else:
        n=random.randint(0,100)
        print(n)
        return test(n)

In [21]:
import numpy as np
np.arange(-1,1,0.1)

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

In [24]:
size=0.5
space=0.1
points=[]
for x in np.arange(-size,size,space):
    for y in np.arange(-size,size,space):
        for z in np.arange(-size,size,space):
            points.append([x,y,z])
len(points)

1000