In [1]:
summery=''' 1|1|UNPC-DESKTOP-69RQV5B|Freq|RB3LYP|6-31G(d)|C2H4|ROOT|15-Jul-2022|0|
 |#N Geom=AllCheck Guess=TCheck SCRF=Check Test GenChk RB3LYP/6-31G(d) 
 Freq||Title Card Required||0,1|C,0.,-0.6654343242,0.|H,0.9236717186,-1
 .2395510205,0.|H,-0.9236717186,-1.2395510205,0.|C,0.,0.6654343242,0.|H
 ,-0.9236717186,1.2395510205,0.|H,0.9236717186,1.2395510205,0.||Version
 =IA32W-G16RevA.03|State=1-AG|HF=-78.5874587|RMSD=8.950e-010|RMSF=5.334
 e-005|ZeroPoint=0.0512214|Thermal=0.0542631|Dipole=0.,0.,0.|DipoleDeri
 v=0.1360233,0.,0.,0.,0.0118945,0.,0.,0.,-0.2710226,-0.0680117,0.078472
 1,0.,0.0588563,-0.0059473,0.,0.,0.,0.1355113,-0.0680117,-0.0784721,0.,
 -0.0588563,-0.0059473,0.,0.,0.,0.1355113,0.1360233,0.,0.,0.,0.0118945,
 0.,0.,0.,-0.2710226,-0.0680117,0.0784721,0.,0.0588563,-0.0059473,0.,0.
 ,0.,0.1355113,-0.0680117,-0.0784721,0.,-0.0588563,-0.0059473,0.,0.,0.,
 0.1355113|Polar=20.4111304,0.,30.7800564,0.,0.,8.5113803|Quadrupole=0.
 6922919,0.7815386,-1.4738305,0.,0.,0.|PG=D02H [C2"(C1.C1),SG(H4)]|NIma
 g=0||0.64069605,0.,0.88063363,0.,0.,0.10755082,-0.26666112,0.12481576,
 0.,0.27661040,0.12108704,-0.13209795,0.,-0.13644898,0.13887345,0.,0.,-
 0.03609523,0.,0.,0.02422768,-0.26666112,-0.12481576,0.,-0.01699043,-0.
 01388051,0.,0.27661040,-0.12108704,-0.13209795,0.,0.01388051,0.0103410
 4,0.,0.13644898,0.13887345,0.,0.,-0.03609523,0.,0.,0.00236447,0.,0.,0.
 02422768,-0.11558121,0.,0.,0.00410370,0.03019080,0.,0.00410370,-0.0301
 9080,0.,0.64069605,0.,-0.58935941,0.,-0.00165620,-0.01353916,0.,0.0016
 5620,-0.01353916,0.,0.,0.88063363,0.,0.,-0.04528424,0.,0.,0.00496194,0
 .,0.,0.00496194,0.,0.,0.10755082,0.00410370,-0.00165620,0.,0.00156320,
 -0.00076972,0.,0.00137425,0.00017864,0.,-0.26666112,0.12481576,0.,0.27
 661040,0.03019080,-0.01353916,0.,-0.00076972,-0.00502930,0.,-0.0001786
 4,0.00145193,0.,0.12108704,-0.13209795,0.,-0.13644898,0.13887345,0.,0.
 ,0.00496194,0.,0.,0.01318542,0.,0.,-0.00864427,0.,0.,-0.03609523,0.,0.
 ,0.02422768,0.00410370,0.00165620,0.,0.00137425,-0.00017864,0.,0.00156
 320,0.00076972,0.,-0.26666112,-0.12481576,0.,-0.01699043,-0.01388051,0
 .,0.27661040,-0.03019080,-0.01353916,0.,0.00017864,0.00145193,0.,0.000
 76972,-0.00502930,0.,-0.12108704,-0.13209795,0.,0.01388051,0.01034104,
 0.,0.13644898,0.13887345,0.,0.,0.00496194,0.,0.,-0.00864427,0.,0.,0.01
 318542,0.,0.,-0.03609523,0.,0.,0.00236447,0.,0.,0.02422768||0.,0.00014
 119,0.,0.00004912,-0.00002057,0.,-0.00004912,-0.00002057,0.,0.,-0.0001
 4119,0.,-0.00004912,0.00002057,0.,0.00004912,0.00002057,0.|||@'''

In [3]:
summery.split('||')[0]

' 1|1|UNPC-DESKTOP-69RQV5B|Freq|RB3LYP|6-31G(d)|C2H4|ROOT|15-Jul-2022|0|\n |#N Geom=AllCheck Guess=TCheck SCRF=Check Test GenChk RB3LYP/6-31G(d) \n Freq'

In [4]:
summery.split('||')[1]

'Title Card Required'

In [5]:
summery.split('||')[2]

'0,1|C,0.,-0.6654343242,0.|H,0.9236717186,-1\n .2395510205,0.|H,-0.9236717186,-1.2395510205,0.|C,0.,0.6654343242,0.|H\n ,-0.9236717186,1.2395510205,0.|H,0.9236717186,1.2395510205,0.'

In [6]:
summery.split('||')[3]

'Version\n =IA32W-G16RevA.03|State=1-AG|HF=-78.5874587|RMSD=8.950e-010|RMSF=5.334\n e-005|ZeroPoint=0.0512214|Thermal=0.0542631|Dipole=0.,0.,0.|DipoleDeri\n v=0.1360233,0.,0.,0.,0.0118945,0.,0.,0.,-0.2710226,-0.0680117,0.078472\n 1,0.,0.0588563,-0.0059473,0.,0.,0.,0.1355113,-0.0680117,-0.0784721,0.,\n -0.0588563,-0.0059473,0.,0.,0.,0.1355113,0.1360233,0.,0.,0.,0.0118945,\n 0.,0.,0.,-0.2710226,-0.0680117,0.0784721,0.,0.0588563,-0.0059473,0.,0.\n ,0.,0.1355113,-0.0680117,-0.0784721,0.,-0.0588563,-0.0059473,0.,0.,0.,\n 0.1355113|Polar=20.4111304,0.,30.7800564,0.,0.,8.5113803|Quadrupole=0.\n 6922919,0.7815386,-1.4738305,0.,0.,0.|PG=D02H [C2"(C1.C1),SG(H4)]|NIma\n g=0'

In [7]:
summery.split('||')[4]

'0.64069605,0.,0.88063363,0.,0.,0.10755082,-0.26666112,0.12481576,\n 0.,0.27661040,0.12108704,-0.13209795,0.,-0.13644898,0.13887345,0.,0.,-\n 0.03609523,0.,0.,0.02422768,-0.26666112,-0.12481576,0.,-0.01699043,-0.\n 01388051,0.,0.27661040,-0.12108704,-0.13209795,0.,0.01388051,0.0103410\n 4,0.,0.13644898,0.13887345,0.,0.,-0.03609523,0.,0.,0.00236447,0.,0.,0.\n 02422768,-0.11558121,0.,0.,0.00410370,0.03019080,0.,0.00410370,-0.0301\n 9080,0.,0.64069605,0.,-0.58935941,0.,-0.00165620,-0.01353916,0.,0.0016\n 5620,-0.01353916,0.,0.,0.88063363,0.,0.,-0.04528424,0.,0.,0.00496194,0\n .,0.,0.00496194,0.,0.,0.10755082,0.00410370,-0.00165620,0.,0.00156320,\n -0.00076972,0.,0.00137425,0.00017864,0.,-0.26666112,0.12481576,0.,0.27\n 661040,0.03019080,-0.01353916,0.,-0.00076972,-0.00502930,0.,-0.0001786\n 4,0.00145193,0.,0.12108704,-0.13209795,0.,-0.13644898,0.13887345,0.,0.\n ,0.00496194,0.,0.,0.01318542,0.,0.,-0.00864427,0.,0.,-0.03609523,0.,0.\n ,0.02422768,0.00410370,0.00165620,0.,0.00137425,-0.0001

In [8]:
summery.split('||')[5]

'0.,0.00014\n 119,0.,0.00004912,-0.00002057,0.,-0.00004912,-0.00002057,0.,0.,-0.0001\n 4119,0.,-0.00004912,0.00002057,0.,0.00004912,0.00002057,0.'

In [1]:
import numpy as np
def get_gridPoints(range,step,ball=False): 
    '''获取空间格点[3,n]'''
    points=[]
    for x in np.arange(-range,range,step):
        for y in np.arange(-range,range,step):
            for z in np.arange(-range,range,step):
                if ball:
                    distance=(x**2+y**2+z**2)**0.5
                    if distance>range:
                        continue
                points.append([x,y,z])
    return np.array(points).T
get_gridPoints(10,0.1,ball=True)

array([[-1.00000000e+01, -9.90000000e+00, -9.90000000e+00, ...,
         9.90000000e+00,  9.90000000e+00,  9.90000000e+00],
       [-3.55271368e-14, -1.40000000e+00, -1.40000000e+00, ...,
         1.40000000e+00,  1.40000000e+00,  1.40000000e+00],
       [-3.55271368e-14, -1.00000000e-01, -3.55271368e-14, ...,
        -1.00000000e-01, -3.55271368e-14,  1.00000000e-01]])

In [3]:
from numba import jit
@jit(nopython=True)
def get_gridPoints(range,step,ball=False): 
    '''获取空间格点[3,n]'''
    points=[]
    for x in np.arange(-range,range,step):
        for y in np.arange(-range,range,step):
            for z in np.arange(-range,range,step):
                if ball:
                    distance=(x**2+y**2+z**2)**0.5
                    if distance>range:
                        continue
                points.append([x,y,z])
    return np.array(points).T
get_gridPoints(20,0.1,ball=True)

array([[-20. , -19.9, -19.9, ...,  19.9,  19.9,  19.9],
       [  0. ,  -1.9,  -1.9, ...,   1.9,   1.9,   1.9],
       [  0. ,  -0.6,  -0.5, ...,   0.4,   0.5,   0.6]])

In [4]:
get_gridPoints(20,0.1,ball=False)

array([[-20. , -20. , -20. , ...,  19.9,  19.9,  19.9],
       [-20. , -20. , -20. , ...,  19.9,  19.9,  19.9],
       [-20. , -19.9, -19.8, ...,  19.7,  19.8,  19.9]])

In [1]:
SP=[
    [
        [0.7868272350e+01, -0.1193324198e+00 , 0.6899906659e-01],
        [0.1881288540e+01, -0.1608541517e+00 , 0.3164239610e+00],
        [0.5442492580e+00,  0.1143456438e+01 , 0.7443082909e+00],
    ],
    [
        [0.1687144782e+00 , 0.1000000000e+01 , 0.1000000000e+01]
    ]
]

In [3]:
for SPi in SP:
    for c,aS,aP in SPi:
        print(c,aS,aP)

7.86827235 -0.1193324198 0.06899906659
1.88128854 -0.1608541517 0.316423961
0.544249258 1.143456438 0.7443082909
0.1687144782 1.0 1.0


In [ ]:
# 定义一个基组的类(数据类型)